version: 0.2
env:
  secrets-manager:
    LOGIN: stage/sonar:SONARTOKEN
    HOST: stage/sonar:HOST
    ORG: stage/sonar:ORG
    PROJECT: stage/sonar:PROJECT
phases:
  install:
    runtime-versions:
      dotnet: 3.x
  pre_build:
    commands:
      - apt-get update
      - apt-get install -y jq
      - dotnet tool install --global dotnet-sonarscanner
      - dotnet tool install --global dotnet-coverage
      - dotnet tool install --global dotnet-reportgenerator-globaltool
  build:
    commands:
      - dotnet sonarscanner begin 
        /k:"$PROJECT"
        /o:"$ORG"
        /d:sonar.login="$LOGIN"
        /d:sonar.host.url="$HOST"
        /d:"sonar.verbose=true"
        /d:sonar.cs.vscoveragexml.reportsPaths="coverage.xml"
        /d:sonar.exclusions="**/*.html, **/*.cshtml, **/*.css, **/*.yml, **/*.json, **/*.js"
      - dotnet build --no-incremental
      - dotnet-coverage collect 'dotnet test' -f xml -o "coverage.xml"
      - dotnet sonarscanner end /d:sonar.login="$LOGIN"
      - if [ $(jq -r '.projectStatus.status' coverage.xml) = ERROR ] ; then $CODEBUILD_BUILD_SUCCEEDING -eq 0 ;fi
